### ISSUE TITLE
rospack depends1 not working

### ISSUE THREAD

**Issue by vmayoral** [ros/meta-ros#108]
While testing `rospack depends1`:

```
rosdep init
Wrote /etc/ros/rosdep/sources.list.d/20-default.list
Recommended: please run

        rosdep update
```

```
rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://github.com/ros/rosdistro/raw/master/rosdep/osx-homebrew.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/gentoo.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/base.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/python.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/ruby.yaml
Hit https://github.com/ros/rosdistro/raw/master/releases/fuerte.yaml
ERROR: unable to process source [https://github.com/ros/rosdistro/raw/master/releases/groovy.yaml]:
        Failed to download target platform data for gbpdistro:
        HTTP Error 404: Not Found
ERROR: unable to process source [https://github.com/ros/rosdistro/raw/master/releases/hydro.yaml]:
        Failed to download target platform data for gbpdistro:
        HTTP Error 404: Not Found
updated cache in /home/root/.ros/rosdep/sources.cache
```

```
rospack depends1 roscpp
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rosdep2/rospack.py", line 55, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/lib/python2.7/site-packages/rosdep2/main.py", line 107, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/python2.7/site-packages/rosdep2/sources_list.py", line 497, in create_default
    matcher = DataSourceMatcher.create_default(os_override=os_override)
  File "/usr/lib/python2.7/site-packages/rosdep2/sources_list.py", line 229, in create_default
    os_name, os_version, os_codename = os_detect.detect_os()
  File "/usr/lib/python2.7/site-packages/rospkg/os_detect.py", line 404, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s"%attempted)
rospkg.os_detect.OsNotDetected: Could not detect OS, tried ['ubuntu', 'rhel', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rosdep2/rospack.py", line 55, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/lib/python2.7/site-packages/rosdep2/main.py", line 107, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/python2.7/site-packages/rosdep2/sources_list.py", line 497, in create_default
    matcher = DataSourceMatcher.create_default(os_override=os_override)
  File "/usr/lib/python2.7/site-packages/rosdep2/sources_list.py", line 229, in create_default
    os_name, os_version, os_codename = os_detect.detect_os()
  File "/usr/lib/python2.7/site-packages/rospkg/os_detect.py", line 404, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s"%attempted)
rospkg.os_detect.OsNotDetected: Could not detect OS, tried ['ubuntu', 'rhel', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
[rospack] Error: could not call python function 'rosdep2.rospack.init_rospack_interface'
```

Seems like a problem at this function:

```
369     def detect_os(self, env=None):
370         """
371         Detect operating system.  Return value can be overridden by
372         the :env:`ROS_OS_OVERRIDE` environment variable.
373         
374         :param env: override ``os.environ``
375         :returns: (os_name, os_version, os_codename), ``(str, str, str)``
376         :raises: :exc:`OsNotDetected` if OS could not be detected
377         """
378         if env is None:
379             env = os.environ
380         if 'ROS_OS_OVERRIDE' in env:
381             splits = env["ROS_OS_OVERRIDE"].split(':')
382             self._os_name = splits[0]
383             if len(splits) > 1:
384                 self._os_version = splits[1]
385                 if len(splits) > 2:
386                     self._os_codename = splits[2]
387                 else:
388                     self._os_codename = ''
389             else:
390                 self._os_version = self._os_codename = ''
391             self._override = True
392         else:
393             for os_name, os_detector in self._os_list:
394                 if os_detector.is_os():
395                     self._os_name = os_name
396                     self._os_version = os_detector.get_version()
397                     self._os_codename = os_detector.get_codename()
398                     self._os_detector = os_detector
399 
400         if self._os_name:
401             return self._os_name, self._os_version, self._os_codename
402         else: # No solution found
403             attempted = [x[0] for x in self._os_list]
404             raise OsNotDetected("Could not detect OS, tried %s"%attempted)

```

Could you please give it a try in qemu? Any ideas?

**Comment by herb-kuta-lge** [comment]
@vmayoral  < Can this issue be closed?

**Comment by vmayoral** [comment]
@herb-kuta-lge it's been a while since this and I don't have time to look at it anymore so sure, let's close it.
