### ISSUE TITLE
Build error for flexbe-onboard

### ISSUE THREAD

**Issue by bchoineubility** [ros/meta-ros#1084]
Hi,

This issue would be similar with [https://github.com/ros/meta-ros/issues/1077](url).

```
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| Traceback (most recent call last):
|   File "/home/bchoi/nvidia-yocto-bsp/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-onboard/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
|     return _run_code(code, main_globals, None,
|   File "/home/bchoi/nvidia-yocto-bsp/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-onboard/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/runpy.py", line 86, in _run_code
|     exec(code, run_globals)
|   File "/home/bchoi/nvidia-yocto-bsp/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-onboard/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/__main__.py", line 92, in <module>
|     _main(sys.argv[1:], "python -m installer")
|   File "/home/bchoi/nvidia-yocto-bsp/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-onboard/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/__main__.py", line 88, in _main
|     installer.install(source, destination, {})
|   File "/home/bchoi/nvidia-yocto-bsp/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-onboard/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/_core.py", line 86, in install
|     for name, module, attr, section in parse_entrypoints(entrypoints_text):
|   File "/home/bchoi/nvidia-yocto-bsp/official_ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/flexbe-onboard/2.3.3-1-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/installer/utils.py", line 221, in parse_entrypoints
|     assert match
| AssertionError
| WARNING: exit code 1 from a shell command.

``` 
Adding the following  clear this issue.

```bitbake
do_configure:prepend() {
     # Fix for error: python3.10/site-packages/installer/utils.py", line 222, in parse_entrypoints
     # assert match
     # This is caused by an invalid entry in the setup.py file
     sed -i "/'flexbe_onboard = flexbe_onboard.flexbe_onboard',/d" setup.py
}

``` 

BR,
Mark

**Comment by robwoolley** [comment]
This should be fixed by this commit: https://github.com/ros/meta-ros/commit/f0d0a112bffad5935745e0bffb52845eaacf8512

Please feel free to reopen if you run into any issues.
