### ISSUE TITLE
dynamic_reconfigure lacks ${PYTHON_PN}-rospkg in its DEPENDS/RDEPENDS

### ISSUE THREAD

**Issue by dkargin** [ros/meta-ros#593]
So each recipe that needs dynamic_reconfigure must add `${PYTHON_PN}-rospkg` to DEPENDS, or fail with error like
```
| Traceback (most recent call last):
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/freenect_stack-0.4.1/freenect_camera/cfg/Freenect.cfg", line 3, in <module>
|     from dynamic_reconfigure.parameter_generator_catkin import *
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/recipe-sysroot/opt/ros/indigo/lib/python2.7/site-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
|     import roslib
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/recipe-sysroot/opt/ros/indigo/lib/python2.7/site-packages/roslib/__init__.py", line 50, in <module>
|     from roslib.launcher import load_manifest
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/recipe-sysroot/opt/ros/indigo/lib/python2.7/site-packages/roslib/launcher.py", line 42, in <module>
|     import rospkg
| ImportError: No module named rospkg
```
when catkin tries to generate dreconf files

**Comment by bulwahn** [comment]
Solution was proposed in #600 and included in pull request #604. Issue is resolved.
