### ISSUE TITLE
Error running roscore 

### ISSUE THREAD

**Issue by jaronski** [ros/meta-ros#611]
hi all,
i am trying to run roscore on a yocto meta-ros bitbaked image. i exported everything from the README and adjusted as follows:
export ROS_ROOT=/opt/ros/indigo
export ROS_DISTRO=indigo
export ROS_PACKAGE_PATH=/opt/ros/indigo/share
export PATH=$PATH:/opt/ros/indigo/bin
export LD_LIBRARY_PATH=/opt/ros/indigo/lib
export PYTHONPATH=/opt/ros/indigo/lib/python3.5/site-packages:/usr/lib/python3.5/site-packages/
export ROS_MASTER_URI=http://localhost:11311
export CMAKE_PREFIX_PATH=/opt/ros/indigo
touch /opt/ros/indigo/.catkin

i added the ROS_USE_PYTHON3 = yes and LICENSE_FLAGS_WHITELIST = "commercial"
when i run roscore i get the error:
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/roscore", line 69, in <module>
    import roslaunch
  File "/opt/ros/indigo/lib/python3.5/site-packages/roslaunch/__init__.py", line 51, in <module>
    from . import param_dump as roslaunch_param_dump
  File "/opt/ros/indigo/lib/python3.5/site-packages/roslaunch/param_dump.py", line 40, in <module>
    import roslaunch.config
  File "/opt/ros/indigo/lib/python3.5/site-packages/roslaunch/config.py", line 45, in <module>
    import rospkg.distro
  File "/usr/lib/python3.5/site-packages/rospkg/distro.py", line 44, in <module>
    import yaml
  File "/usr/lib/python3.5/site-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax

Can anyone point me in a direction solving this?

thanks and best regards

**Comment by herb-kuta-lge** [comment]
@jaronski < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).

**Comment by aarsht7** [comment]
I had the same problem as there were multiple versions of python present on the system.

Solution: `ln -sf /usr/bin/python3 /usr/local/bin/python`

You can put it in ~/.bashrc to avoid it in future
