### ISSUE TITLE
ERROR: Unable to start bitbake server while building yocto project 

### ISSUE THREAD

**Issue by akbarsaleemt** [ros/meta-ros#860]
Hi Team,
I am using ubuntu 20.04 on WSL . tried to compile yocto project but getting below error .
Thanks in advance.

**Error:**
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/atakkasila/akbar/MDM9607/apps_proc/poky/build/conf/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 2753 at 2021-06-07 18:06:47.948772 ---
ERROR: Traceback (most recent call last):
  File "/home/atakkasila/akbar/MDM9607/apps_proc/poky/bitbake/lib/bb/cookerdata.py", line 168, in wrapped
    return func(fn, *args)
  File "/home/atakkasila/akbar/MDM9607/apps_proc/poky/bitbake/lib/bb/cookerdata.py", line 193, in parse_config_file
    return bb.parse.handle(fn, data, include)
  File "/home/atakkasila/akbar/MDM9607/apps_proc/poky/bitbake/lib/bb/parse/__init__.py", line 107, in handle
    return h['handle'](fn, data, include)
  File "/home/atakkasila/akbar/MDM9607/apps_proc/poky/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 121, in handle
    abs_fn = resolve_file(fn, data)
  File "/home/atakkasila/akbar/MDM9607/apps_proc/poky/bitbake/lib/bb/parse/__init__.py", line 125, in resolve_file
    raise IOError(errno.ENOENT, "file %s not found in %s" % (fn, bbpath))
FileNotFoundError: [Errno 2] file conf/bitbake.conf not found in /home/atakkasila/akbar/MDM9607/apps_proc/poky/build/conf/build

ERROR: Unable to parse conf/bitbake.conf: [Errno 2] file conf/bitbake.conf not found in /home/atakkasila/akbar/MDM9607/apps_proc/poky/build/conf/build

**Comment by shr-project** [comment]
This doesn't seem related to meta-ros, but the way how you configured your poky build.
